name: sup_gen_sqler
description: Package contains sqls and database handler for sup_gen_runner
version: 1.0.0
homepage: https://github.com/woueziou/sup_gen.git
repository: https://github.com/woueziou/sup_gen.git
documentation: https://github.com/woueziou/sup_gen.git
issue_tracker: https://github.com/woueziou/sup_gen/issues
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  postgres: ^3.4.3
  dartx: ^1.2.0
  sup_gen_model: any
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
