name: sup_gen_model
description: Package contains model for sup_gen_runner and sup_gen_sqler
version: 1.0.1
homepage: https://github.com/woueziou/sup_gen.git
repository: https://github.com/woueziou/sup_gen.git
documentation: https://github.com/woueziou/sup_gen.git
issue_tracker: https://github.com/woueziou/sup_gen/issues

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  build: ^2.4.1
  analyzer: '>=5.2.0 <7.0.0'  
  source_gen: ^1.4.0
  json_annotation: ^4.4.0
  # path: ^1.8.0

dev_dependencies:
  build_config: ^1.1.1  
  build_runner: ^2.4.6  
  lints: ^2.1.1  
  json_serializable: ^6.0.0
  test: ^1.24.8
